In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
%matplotlib inline

In [48]:
np.random.seed(1234)
N = 1000

#### data generating

The model:

$$
y_i = 1 + x_{1i} + x_{2i} + \epsilon_i
$$

where $x_{1i}$, $x_{2i}$, $ε_i$ are mutually independent standard normal random variables.

In [49]:
# generating standard normal dist random numbers
x1 = np.random.normal(size=N)
x2 = np.random.normal(size=N)
ε = np.random.normal(size=N)

y = 1 + x1 + x2 + ε

## do OLS regression manually

(a)

In [50]:
X = np.empty((N, 3)) # N by 3 matrix
X[:, 0] = 1 # consta_nt term
X[:, 1] = x1 # fill with x1 values
X[:, 2] = x2 # fill with x2 values

In [51]:
β_hat = np.linalg.inv(X.T @ X) @ (X.T @ y)
β_hat

array([1.04229289, 1.03666859, 1.05311438])

(b)

In [52]:
ϵ_hat = y - X @ β_hat

In [60]:
np.isclose((X.T @ ϵ_hat), 0)

array([ True,  True,  True])

(c)

In [61]:
np.isclose((X.T @ ϵ), 0)

array([False, False, False])

In [62]:
X.T @ ϵ

array([45.08823244, 35.94711557, 54.41040244])

(d)

The auxiliary regression model:

$$
x_{1i} = \alpha + \gamma x_{2i} + \nu_i
$$

In [65]:
X_aux = np.empty((N, 2))
X_aux[:, 0] = 1
X_aux[:, 1] = x2

In [66]:
γ_hat = np.linalg.inv(X_aux.T @ X_aux) @ (X_aux.T @ x1)
γ_hat

array([0.01532636, 0.00991858])

In [67]:
ν_hat = x1 - X_aux @ γ_hat

In [72]:
β1_hat = (ν_hat.T @ y) / (ν_hat.T @ ν_hat)

In [75]:
β1_hat, β_hat[1]

(1.0366685948557743, 1.0366685948557743)

(e)

$$
E[x_i x_i^\prime] = E[[] x_i^\prime]
$$

## do OLS regression with StatsModels

In [79]:
import statsmodels.api as sm

In [81]:
results = sm.OLS(y, X).fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.685
Model:                            OLS   Adj. R-squared:                  0.684
Method:                 Least Squares   F-statistic:                     1083.
Date:                Wed, 16 Jan 2019   Prob (F-statistic):          9.70e-251
Time:                        23:01:58   Log-Likelihood:                -1408.4
No. Observations:                1000   AIC:                             2823.
Df Residuals:                     997   BIC:                             2838.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.0423      0.031     33.225      0.0

In [82]:
# access the estimated parameters
results.params

array([1.04229289, 1.03666859, 1.05311438])

In [87]:
# test the residuals and regressors are orthogonal
np.isclose(X.T @ results.resid, 0)

array([ True,  True,  True])