## Problem Set 6 - Questions 1 and 2
### David Zynda

__Question 1__
(a)

In [15]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1234)

M = 5
obs = np.random.uniform(-0.5, 0.5, size=M)
np.mean(obs)

0.06333807045168227

(b)

In [6]:
N = 1000
means = np.ones((N, 1))

for i in range(0,N):
    means[i,:] = np.mean(np.random.uniform(-0.5, 0.5, size=M))


(c) I ran out of time to figure out matplotlib histograms. Here is a numerical one:

In [17]:
np.histogram(means, bins = 10, range = (-1, 1))


(array([  0,   0,   0,  71, 431, 419,  79,   0,   0,   0], dtype=int64),
 array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]))

In [18]:
N = 1000
M = 20
means = np.ones((N, 1))

for i in range(0,N):
    means[i,:] = np.mean(np.random.uniform(-0.5, 0.5, size=M))
    
np.histogram(means, bins = 10, range = (-1, 1))

(array([  0,   0,   0,   0, 507, 492,   1,   0,   0,   0], dtype=int64),
 array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]))

(e) 

In [19]:
N = 1000
M = 80
means = np.ones((N, 1))

for i in range(0,N):
    means[i,:] = np.mean(np.random.uniform(-0.5, 0.5, size=M))
    
np.histogram(means, bins = 10, range = (-1, 1))

(array([  0,   0,   0,   0, 491, 509,   0,   0,   0,   0], dtype=int64),
 array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]))

(f) see R markdown document

__Question 2__ (a) and (b) see above. Below: (c) 

In [21]:
N = 1000
M = 5
means = np.ones((N, 1))

for i in range(0,N):
    means[i,:] = np.mean(np.random.uniform(-0.5, 0.5, size=M))
    
np.histogram((np.sqrt(M) * means), bins = 10, range = (-1, 1))

(array([  3,  13,  73, 151, 240, 270, 170,  65,  14,   1], dtype=int64),
 array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]))

(d)

In [22]:
N = 1000
M = 20
means = np.ones((N, 1))

for i in range(0,N):
    means[i,:] = np.mean(np.random.uniform(-0.5, 0.5, size=M))
    
np.histogram((np.sqrt(M) * means), bins = 10, range = (-1, 1))

(array([  3,  17,  52, 168, 262, 255, 158,  66,  18,   1], dtype=int64),
 array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]))

(e) 

In [24]:
N = 1000
M = 80
means = np.ones((N, 1))

for i in range(0,N):
    means[i,:] = np.mean(np.random.uniform(-0.5, 0.5, size=M))
    
np.histogram((np.sqrt(M) * means), bins = 10, range = (-1, 1))

(array([  3,  21,  80, 160, 270, 235, 144,  65,  17,   4], dtype=int64),
 array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]))